### PR TITLE
Issue #1082 - Update AO examples in request flow

### LINKED ISSUE #1082: Authorizing official: update AO examples within the request flow
### Issue Description

In #992, we added new AO examples for each org type on beta.get.gov ([Eligibility](https://beta.get.gov/domains/eligibility/) page). We need to make the same changes in the domain request flow. 

AC: 

- [x] Update the examples for each org type on the "Authorizing Official" step of the request flow. (i.e. match the examples used on the Eligibility page)
- [x] Update the related [Google doc](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.2bn6wsx) to reflect the changes.

### Additional Context (optional)

These updates need to be made in a separate GitHub space, so making this a separate story from #992 

### Issue Links

_No response_

### PR DESCRIPTION
**Pull request by kristinacyin**
## Ticket

Resolves #1082 

## Changes

- Updated ao_example.html with content from ["Eligibility for .gov domains" page](https://beta.get.gov/domains/eligibility/) in info site
- Updated test_views.py since first line of ao_example.html was changed

## Setup

Please visit [getgov-ky.app.cloud.gov](https://getgov-ky.app.cloud.gov/) and visit the Authorizing official page (/authorizing_official) request page. The Authorizing Official example provided (located after the first paragraph and before "We typically don’t reach out to the authorizing official") matches the content found on the ["Eligibility for .gov domains" page.](https://beta.get.gov/domains/eligibility/#you-must-have-approval-from-an-authorizing-official-within-your-organization) for all of the different organization types:

- [ ] Federal - Executive
- [ ] Federal - Judicial
- [ ] Federal - Legislative
- [ ] Interstate
- [ ] State
- [ ] Tribal
- [ ] County
- [ ] City
- [ ] Special district
- [ ] School district

You can also see screenshots in the comment history below for convenience.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari
- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari
- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

See comment history below for screenshots (didn't want to clog up this area).

### CODE REVIEW

**Comment by kristinacyin** [comment]
**Federal - Executive**

Before:

After:

**Comment by kristinacyin** [comment]
### Federal - Legislative

Before:

After:
Screenshot 2023-12-12 at 5 11 41 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### Interstate

Before:

After:
Screenshot 2023-12-12 at 5 13 31 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### State

Before:

After:
Screenshot 2023-12-12 at 5 21 36 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### Tribal

Before:

After:
Screenshot 2023-12-12 at 5 24 29 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### County

Before:

After:
Screenshot 2023-12-12 at 5 26 53 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### City

Before:

After:
Screenshot 2023-12-12 at 5 28 08 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### Special district

Before:

After:
Screenshot 2023-12-12 at 5 29 22 PM

Reference: AO example provided in info site.

**Comment by kristinacyin** [comment]
### School district

Before:

After:
Screenshot 2023-12-12 at 5 30 46 PM

Reference: AO example provided in info site.

**Review by michelle-rago — APPROVED** [review]
LGTM!

**Comment by Katherine-Osos** [comment]
@kristinacyin UI looks great, just one edit: 
- Tribal gov: Link for “Bureau of Indian Affairs” should display the external-link icon.

Also, I noticed the corresponding [Google doc](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.2bn6wsx) hasn't been updated yet with these changes. Were you waiting to do that after approval?

**Review by Katherine-Osos — APPROVED** [review]

**Comment by Katherine-Osos** [comment]
Looks great - just approved!

**Pull request merged**
