### PR TITLE
Issue #1216 - checking transition domains on each login rather than on first login …

### LINKED ISSUE #1216: Move first_login logic so that it occurs on all logins
### Issue description

Currently, we have a function (first_login in User.py) that is triggered when it is the users first time logging into our system. In this function, we are checking 1.) are they part of a transition domain, if so make sure there is a domain inviation for them and a domain information object, 2) for all domain invitations they have,  we add a user domain role to their account so they can access the domains.

The problem is when it comes time for transition, if anyone logs into our system BEFORE we run the migration scripts then they will already have a User row and account on our system and they will not trigger the checks above. This is a bit of a race condition that is easily avoided by just having the first_login logic triggered on every login.

### Acceptance criteria

- [ ] rename first_login and all uses of it  (as it is no longer used just at first login
- [ ] move the formerly named first_login to be called for all users. 
- [ ] add or update existing unit tests 

### Additional context

To accomplish the second AC above I suggest moving the highlight lint (user.first_login()) in the backend.py Authenticate function to right above the return on line 59 so it is called on each user. See picture below:
image

### Links to other issues

_No response_

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #1216

## Changes

- Domain information and transition domains are checked on each login.  This used to be only on first login.

## Context for reviewers

Transition domains may be created and associated with email addresses of existing users.  So, the checking for domains without domain information and transition domains without domains needs to happen on each login, not just on the initial account creation.

To verify, you will only need an existing account, and then follow the steps under Setup.

## Setup

You will need to log into the django admin once and set up the transition domain.  Then log out and then log back in and verify that the domain and domain information have been properly initialized.  Below are the steps:

Login first time:
Go to admin on dk sandbox: https://getgov-dk.app.cloud.gov/admin
Click on Transition domains.
You will need to create a new transition domain.  Click Add to do so.  Username must be set to the email address associated with your account.  Domain name is the new domain name.  And Status is Ready.  Don't click Email sent.  And then hit Save.
Now log out.

Login second time:
Go to home page on dk sandbox: https://getgov-dk.app.cloud.gov
You should now see the domain you created under Domains.  Click on Manage to verify that the domain can be interacted with and managed.
Next, go to the admin to verify that the domain and domain information objects have been created.
Go to admin on dk sandbox:  https://getgov-dk.app.cloud.gov/admin
Click domains - you should see your domain
Click Domain information - you should see your domain

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [x] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [x] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [x] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by therealslimhsiehdy** [comment]
**Question? Slightly blocking comment? Bug?** 

The code looks like a simple change, however I'm running into an issue when I'm following your steps.

Everything in step 1 looks great, and when I login a second time to [your sandboxI]( https://getgov-dk.app.cloud.gov/) I see my domain created, domain + domain information. HOWEVER when I click on "Manage" to verify that the domain can be interacted with and managed I get a 500 error. 

Would you mind seeing if you're getting this error as well, or if it's just a weird 1 off with me?

**Review by therealslimhsiehdy — COMMENTED** [review]
**Question? Slightly blocking comment? Bug?**

The code looks good (great diagram btw), however I'm running into an issue when I'm following your steps.

Everything in step 1 looks great, and when I login a second time to [your sandbox](https://getgov-dk.app.cloud.gov/) I see my domain created, domain + domain information. HOWEVER when I click on "Manage" to verify that the domain can be interacted with and managed I get a 500 error.

Would you mind seeing if you're getting this error as well, or if it's just a weird 1 off with me?

**Review by therealslimhsiehdy — APPROVED** [review]

**Comment by dave-kennedy-ecs** [comment]
> **ETA:** Nvm lols @ me, just saw that your other PR addresses the bug! I've approved with the assumption that your other ticket will resolve since the code change is simple here.
> 
> **ETA #2:** Sorry for the morning chaos, just realized that the other PR was NOT addressing what I thought it was. Please let me know if you're also seeing the bug I mentioned below. (I left ETA #1 in case you were like "why did becca approve then remove her approval" LOL)
> 
> **Question? Slightly blocking comment? Bug?**
> 
> The code looks good (great diagram btw), however I'm running into an issue when I'm following your steps.
> 
> Everything in step 1 looks great, and when I login a second time to [your sandbox](https://getgov-dk.app.cloud.gov/) I see my domain created, domain + domain information. HOWEVER when I click on "Manage" to verify that the domain can be interacted with and managed I get a 500 error.
> 
> Would you mind seeing if you're getting this error as well, or if it's just a weird 1 off with me?

I can reproduce.  Let me take a look

**Review by therealslimhsiehdy — APPROVED** [review]

**Review by neilmb — APPROVED** [review]
LGTM. 

Very non-blocking comment this week: is there any way to make a unit test to demonstrate that we are picking up invitations on subsequent logins? I suspect no, because this callback code is actually never called in our test suite because we don't log users in with OIDC.

**Pull request merged**
