### PR TITLE
Issue #2274: removed data calculation from renew_domain DJA function

### LINKED ISSUE #2274: Update Renewal feature
### Issue description

The registry is now able to renew domains to 1 year from the current date always. This means we no longer need to do the following:
1. calculate the number of years the domain needs to be extended by (it should always be one for now)
2. calculate the expected expiration date by assuming the expiration's date month and day will not change. It will in fact change to the current date. 

Right now our registrar calculates the expiration date years needed to bring the domain up to about a year in the future and assumes data and month always remain unchanged. This means we show this expected date on django admin, which is now wrong and we have functions we can remove now.

### Acceptance criteria

- [ ] In admin.py _get_calculated_years_for_exp_date is removed as we will just extend 1 year
- [ ] in admin.py _set_expiration_date is updated so that extended_expiration_date is always one year from the current date
- [ ] unit tests updated as needed
- [ ] developer removes any other year calculation logic/comments regarding domain renewal that is not listed here and adjusts it to the new logic

### Additional context

_No response_

### Links to other issues

resulted from #2003

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #2274 

## Changes

- Removed date calculation on renew_domain function in django admin
- Set renew_domain to renew domain 1 year from today
- Updated modal to not display an estimated renew date

## Context for reviewers

Navigate to django admin.  Select a domain.  Click the Extend expiration date link in the upper right of the change form.  Confirm the update.  Verify that the new expiration date is one year from today

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [x] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Review by kristinacyin — CHANGES_REQUESTED** [review]
I tried extending the expiration date for the domain "ago-song-process.gov", but no matter how many times I try, the expiration date stays the same (June 25, 2025). See screenshot:

screenshot

I tried using Incognito windows in case this was a cookies issue, but the expiration date still didn't change. 

Also, I really like the warning message! Would it be ok add the current expiration date of the domain to the message as well? 


warning

Maybe something like:

> Domain: **ago-song-process.gov**
> Current expiration date: **June 25, 2025**

**Comment by dave-kennedy-ecs** [comment]
> I tried extending the expiration date for the domain "ago-song-process.gov", but no matter how many times I try, the expiration date stays the same (June 25, 2025). See screenshot:

The ticket indicated that the renew function should always renew to 1 year from today's date.

**Comment by kristinacyin** [comment]
> > I tried extending the expiration date for the domain "ago-song-process.gov", but no matter how many times I try, the expiration date stays the same (June 25, 2025). See screenshot:
> 
> The ticket indicated that the renew function should always renew to 1 year from today's date.

Got it, that makes sense. Would it be possible to edit the warning message, as indicated in my original comment? Thank you!

**Review by kristinacyin — APPROVED** [review]
Thank you for making the changes! Also, I really liked @zandercymatics's idea of disabling / greying out the functionality if the expiration date can't be changed (if date has already been updated and can't be extended any further) with a note on why. That being said, I think the current work already fulfills the AC of the ticket so I will go ahead and approve this. Great work! 🎆

**Comment by kristinacyin** [comment]
Also, FYI it worked before but after logging back in, I'm getting a server error when I try to see the details of a domain (click on a domain name in the Domains table). Is it because of the waffle flag?

image

**Review by CocoByte — APPROVED** [review]
LGTM! (tested and verified on -bob)

**Comment by rachidatecs** [comment]
> Also, FYI it worked before but after logging back in, I'm getting a server error when I try to see the details of a domain (click on a domain name in the Domains table). Is it because of the waffle flag?
> 
> image

Still seeing an issue @kristinacyin?

**Comment by kristinacyin** [comment]
> > Also, FYI it worked before but after logging back in, I'm getting a server error when I try to see the details of a domain (click on a domain name in the Domains table). Is it because of the waffle flag?
> > image
> 
> Still seeing an issue @kristinacyin?

It's fine now!

**Pull request merged**
