### PR TITLE
Issue #1839: domain request form layout changes

### LINKED ISSUE #1839: Improving the layout of domain requests for analysts
### Problem:
Analysts need to scroll and sometimes navigate to different pages to collect the information most useful to them when adjudicating a request. Creator, Submitter, and AO are of particular interest to them in quickly assessing their confidence with the supplied information.

### Solution:
(based on UX research and feedback from Alex)
Bring the most relevant information to the TOP of the request form, in the Analyst view, so that the analysts save time and have a delightful experience.

See the Miro Wireframe for layout.
[Layout #2](https://miro.com/app/board/uXjVNtCl1JY=/?moveToWidget=3458764580518702651&cot=14)

### Acceptance criteria

- [ ] Admin Domain Request page layout is updated per the Miro
- [ ] Review with designer and @amcelya for acceptance

### Additional context

_No response_

### Links to other issues

Blocks: #1852

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #1839 

## Changes

- Modified domain application form layout according to Mira board
- Modified domain and domain information form layout to mirror the domain application form layout in Mira board
- Changed font size of h2 in django admin

## Context for reviewers

Note that the multi-selects refactoring is in a different ticket, which has not yet been merged at the time of this PR creation, so you will still see the old multi-selects in the form.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by Katherine-Osos** [comment]
@dave-kennedy-ecs I've been reviewing this and it looks great. Question for you - why is the ".gov domain" section blank on the "Domains" page? When viewing "Domain Information" that section is populated ... but it's not populated on the corresponding "Domains" page.

(By the way, I still can't access slack, so I can't communicate with you there.)

**Comment by Katherine-Osos** [comment]
@dave-kennedy-ecs Also, in the multi-select boxes for "alternative domains" etc (which will soon only be viewable to superusers), it looks like the table headings are reflecting the new, larger h2 heading. Could that use an h3 or something else to make those multi-select headings smaller?

**Comment by dave-kennedy-ecs** [comment]
> @dave-kennedy-ecs I've been reviewing this and it looks great. Question for you - why is the ".gov domain" section blank on the "Domains" page? When viewing "Domain Information" that section is populated ... but it's not populated on the corresponding "Domains" page.

The domain is the only piece of information in this section.  I think the domain is excluded because the DomainInformation is included inline from the domain, and the relationship between domain and domain information cannot be changed in this context.  I am not 100% sure, but this is how I am reading the django admin code.

I can remove the entire .gov domain section from the Domain admin form.  Do you think I should do that?

**Review by Katherine-Osos — APPROVED** [review]

**Review by abroddrick — APPROVED** [review]
Approved, but want to wait on merging this given the recent Application issue, this migration number may need to change

**Pull request merged**
