### PR TITLE
Issue #956: Alternative domains subheading (DK SANDBOX)

### LINKED ISSUE #956: Add subheading for "alternative domains" on application review page and emails
### Issue Description

On the application review page (last page of the domain request process) and within auto-response emails, we display an overview of a user's application details. And currently, any requested "alternative domains" are grouped with the primary domain the user requested (under the same heading). We need to separate the alternative domains to live under their own heading. 

This update was already made to the "Manage" page for submitted applications. The change simply need to be applied to these other instances. (reference #685) 

**AC:** 
Split alternative domains under their own heading on: 

- [ ] Application review page
- [ ] All application auto-response emails

Ensure this matches the implementation used for the application "Manage" page.

### Additional Context

_No response_

### Issue Links

#685

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #956 

## Changes

- Added subheading to application review page in application process
- Added alternative domains subheading to application summary in email when application submitted

## Context for reviewers

Screenshots down below.  Both changes can be tested by submitting a new application.  May be worth testing both the case when there are Alternative domains, and when there are not Alternative domains in the application.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [x] Checked that the design translated visually
- [x] Checked behavior
- [x] Checked different states (empty, one, some, error)
- [x] Checked for landmarks, page heading structure, and links
- [x] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [x] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

image

image

### CODE REVIEW

**Review by gabydisarli — CHANGES_REQUESTED** [review]
I'm noticing that the page titles + body copy are 16px, while the secondary question (alternative domain or No other employees from your organization?) are set in 16.96px. It seems like these are getting some sort of optical sizing adjustment depending on the browser, while the others are hard coded to be 16px. This might happen for other questions that trigger that secondary treatment on the review page so it would be good to review those as well. 

Screenshot 2024-01-22 at 1 00 33 PM

**Review by zandercymatics — APPROVED** [review]
LGTM. Everything worked, and I don't see any issues with the code other than the small styling differences gaby pointed out

**Review by gabydisarli — COMMENTED** [review]
Sorry for the delay. I see your change but something still didn't feel quite right. I've played around with inspector to try out some different styles. This feels right.
Screenshot 2024-01-24 at 4 03 39 PM

**Comment by rachidatecs** [comment]
> Sorry for the delay. I see your change but something still didn't feel quite right. I've played around with inspector to try out some different styles. This feels right. Screenshot 2024-01-24 at 4 03 39 PM

The markup should stay the same as it is more semantic but we'll make those look the way you want them to.

**Review by therealslimhsiehdy — APPROVED** [review]
LGTM!

**Review by gabydisarli — APPROVED** [review]
love it!

**Pull request merged**
