### PR TITLE
#2777: updated error messages for zip codes and email addresses

### LINKED ISSUE #2777: Update generic error messaging for zip code and email address
### Issue description

A couple of fields still display generic error messaging when the field is left blank: "This field is required." 

We need to update the messaging to be more specific. The updates should apply to all instances of the fields, in org model and non-org model.

### Acceptance criteria
These updates apply to relevant pages in the org model AND non-org model setup.

- [x] On the "Organization" page:
  - [x] When zip code is required and left blank, update error message to read: 
    - Enter a 5-digit or 9-digit ZIP code, like 12345 or 12345-6789.
  - [x] When zip code uses wrong format, update the error message to match the message listed above. (we want them to be consistent)
- [x] On the "add a domain manager" page:
  - [x] When email address is required and left blank, update error message to read: 
    - Enter an email address in the required format, like name@example.com.
- [x] Review registrar and verify other instances where these fields appear show this updated messaging

### Additional context

note to dev, this is just error message updates, you don't need to write unit tests for this, manually testing is sufficient

### Links to other issues

_No response_

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #2777 

## Changes

- Changed email address and zip code error message throughout the app

## Context for reviewers

Note that ZIP is capitalized in this ticket. Please verify that this is supposed to be capitalized.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by gabydisarli** [comment]
@dave-kennedy-ecs I'll be doing design review

**Review by therealslimhsiehdy — APPROVED** [review]
Tried to screenshot as many as I could, LGTM!

Screenshot 2024-10-03 at 1 14 06 PM
Screenshot 2024-10-03 at 1 14 19 PM
Screenshot 2024-10-03 at 1 14 37 PM
Screenshot 2024-10-03 at 1 15 08 PM
Screenshot 2024-10-03 at 1 15 29 PM
Screenshot 2024-10-03 at 1 16 59 PM
Screenshot 2024-10-03 at 1 17 26 PM

**Comment by dave-kennedy-ecs** [comment]
I deployed to [https://getgov-hotgov.app.cloud.gov](hotgov)

**Comment by gabydisarli** [comment]
@dave-kennedy-ecs I don't see the zip code update on the [organization page ](https://getgov-rjm.app.cloud.gov/organization/)in org model
Screenshot 2024-10-09 at 3 13 46 PM

**Comment by gabydisarli** [comment]
also not seeing it on the non-org model organization page 
Screenshot 2024-10-09 at 3 23 32 PM

**Comment by gabydisarli** [comment]
I'm not seeing the changes in a couple other areas so I'm assuming there may be something wrong with the PR at the moment.

**Comment by dave-kennedy-ecs** [comment]
Fixes are restaged to [RJM sandbox](https://getgov-rjm.app.cloud.gov/)

**Comment by gabydisarli** [comment]
Checked error messages across the following pages and everything looks good

### Non Org model
**Domain Mgmt**
- Organization page (zip)
- Add a domain manager (email)
- Senior official (email)
- Security email (email)

**Request form**
- Organization page (zip)
- Other employees (email)
- Senior official (email)


### Org Model
Domain Mgmt
- Add a domain manager (email)
- Security email (email)

**Org info**
- Organization page (zip)

**Review by gabydisarli — APPROVED** [review]

**Comment by gabydisarli** [comment]
non-blocking: I noticed we have some unneccesary padding being added on on input fields when the helper text is present that leaves a wide gap between the helper text and the error message below it. This wasn't introduced in your PR, but wanted to call it out as I see it across all instances of input component with helper text when an error is present. 
Screenshot 2024-10-11 at 3 18 13 PM

**Comment by dave-kennedy-ecs** [comment]
> non-blocking: I noticed we have some unneccesary padding being added on on input fields when the helper text is present that leaves a wide gap between the helper text and the error message below it. This wasn't introduced in your PR, but wanted to call it out as I see it across all instances of input component with helper text when an error is present. Screenshot 2024-10-11 at 3 18 13 PM

cc: @abroddrick

**Pull request merged**
