### PR TITLE
Redirect to get.gov after logout

### LINKED ISSUE #489: Redirect logout to {beta.}get.gov info site
Now that we have the `cloud.gov Pages` site setup at get.gov, we should redirect logout actions to that site. 

As a logged-in user of the registrar
I want to be redirected to the new get.gov informational site when I log out
So that I stay in the .gov experience rather than login.gov

AC:
- [ ] **Given** a logged-in user on the .gov registrar, **when** I logout and also choose "Yes, sign out of login.gov," **then** I am redirected to the get.gov as an unauthenticated user.
- [ ] Language on login.gov screen reads "Do you want to sign out of Login.gov and return to **get.gov**?

Image

### Additional Context:
Currently, if we select to "return to the .gov registrar," we go back to login.gov.... and if we select to go back to the .gov registrar, we get a nasty 401 error because we aren't logged in anymore.

### Links to related issues
🔄 #1509

### PR DESCRIPTION
**Pull request by neilmb**
# 489. Redirect to get.gov after logout from manage.get.gov

Resolves #489

## Changes

After logging out, redirect to https://get.gov using Django's LOGOUT_REDIRECT_URL setting.

## Context for reviewers

This prevents the surprising experience we have now of logging out of manage.get.gov and ending up back at Login.gov because we redirected to a page that requires users to be logged in.

## Setup

Run this locally or on a sandbox, log in and then click "Sign out" in the top right and you should end up at get.gov.

#### Satisfied acceptance criteria and met development standards

- [X] Met the acceptance criteria, or will meet them in a subsequent PR
- [X] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [X] Messaged on Slack or in standup to notify the team that a PR is ready for review

#### Validated user-facing changes (if applicable)

- [X] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Review by zandercymatics — APPROVED** [review]
LGTM!

Question unrelated to your changes/ticket but, is it possible to change this text through our config somewhere, or is that login.gov's side? We may want to consider changing this in a future ticket? cc: @cisagov/gov-designers (for input) and @vickyszuchin  
image
image

**Comment by gabydisarli** [comment]
@zandercymatics can you document where you see those messages? I'm trying to wrap my head around what messaging we have where.

**Comment by neilmb** [comment]
@zandercymatics @gabydisarli That text is specified on the Login.gov application configuration and users see it when they log in and log out. We can only change the "friendly name" part of that message that says either "CISA .gov registrar (staging)" or currently ".gov Registrar" on our production application. The ticket #489 specifies making that friendly name say "get.gov" for production.

**Comment by neilmb** [comment]
@Katherine-Osos This is now deployed on https://getgov-ko.app.cloud.gov/

**Review by Katherine-Osos — APPROVED** [review]

**Pull request merged**
