### PR TITLE
Issue #1922: Added column that indicates whether Contact is also a User

### LINKED ISSUE #1922: Django admin: Add column that indicates whether Contact is also a "user"
### Issue description

Within the Contacts table in the admin, we currently have columns for the contact's name and email address. It would also be helpful to know if the contact is a "user" in the system.  (i.e. not all contacts are users)

### Acceptance criteria

- [ ] Within the Contacts table, add a column for "Is user" (after the email column) that indicates yes/no whether the contact is also a "user" of the admin

### Additional context

This is an update that came out of the [recent audit](https://docs.google.com/spreadsheets/d/1dXe28ZpyghFpxB_T-GZsDpFUKb96AdztsNPhFL0BvpE/edit#gid=616839927) of Django field labels.

### Links to other issues

_No response_

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #1922 

## Changes

- In DjA, Contacts table, added a column after email which indicates whether a Contact is also a User

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by Katherine-Osos** [comment]
@dave-kennedy-ecs This looks great. Two things:
- The "is user" column should be sortable
- Are you able to add tooltips to the icons?

**Comment by dave-kennedy-ecs** [comment]
> @dave-kennedy-ecs This looks great. Two things:
> 
> * The "is user" column should be sortable
> * Are you able to add tooltips to the icons?

I have made the column sortable.  Don't know about tooltips, will have to look into this.  Do you prefer the icon to be text instead?  Yes/No or True/False?

**Comment by Katherine-Osos** [comment]
> I have made the column sortable. Don't know about tooltips, will have to look into this. Do you prefer the icon to be text instead? Yes/No or True/False?

@dave-kennedy-ecs Thanks for adding sorting! For accessibility, we try to avoid letting an icon stand on it's own. But if that gets tricky in Django, then simply using text is ok. i.e. I'm fine with switching to yes/no rather than modifying Django defaults.

**Review by therealslimhsiehdy — APPROVED** [review]
Screenshot 2024-04-16 at 10 36 51 AM

Code LGTM + confirmed on sandbox as well -- will let design make the confirming decision.

Quick question: Just to confirm, by "Contact is also a User" meaning the contact that is being shown is a "Yes" in that column if they are a Superuser or Analyst, correct?

**Review by Katherine-Osos — APPROVED** [review]
LGTM!

**Pull request merged**
