### PR TITLE
Revert "#3074 - Change (margin/padding) responsive layouts - [AB]"

### PR DESCRIPTION
**Pull request by CocoByte**
Reverts cisagov/manage.get.gov#3220

### CODE REVIEW

**Comment by gabydisarli** [comment]
Scanned through all the org model pages. Most of the pages look great! Besides the bug, there are some changes requested and I've laid it all out on this [Figma mockup](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=14558-10163&t=89CWs2p3mk775pwQ-11) to show which ones are needing adjustment and which ones are approved.

**Comment by gabydisarli** [comment]
I scanned through the non-org model pages and left notes on those in the same Figma mockup. Thank you!

**Review by abroddrick — APPROVED** [review]
Approving revert

**Comment by gabydisarli** [comment]
Looks great! Approved

**Pull request merged**
