### PR TITLE
Issue #1073:  admin multi selects

### LINKED ISSUE #1073: Django Admin: Improve experience for updating fields with multiple values
### Story

As a CISA analyst
I want to easily update entries that allow multiple inputs (websites, other contacts)
so that the process is efficient and I don't accidentally override the user's original inputs

### Acceptance Criteria

- Analysts can easily see what the registrant originally put in their application
- Analysts can easily edit or add new entries, as needed.

### Additional Context

_No response_

### Issue Links

_No response_

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #1073 

## Changes

- Multi-list selects implemented for:
  - Domain:  Other contacts
  - DomainInformation:  Other contacts
  - DomainApplication:  Current websites, Alternative domains, Other contacts
  - Extended the implementation of the multi-list selects above to allow for change/delete/view buttons in addition to add in the related widget.

## Context for reviewers

In django admin, review the multi-selects for the fields mentioned in the Changes above. Select one item from the list on the right and test the change, delete and view buttons.

Screenshot of Current websites and Alternative domains in the section below

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [x] Pulled this branch locally and tested it
- [x] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [x] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

image

### CODE REVIEW

**Review by zandercymatics — APPROVED** [review]
LGTM code wise and functionality wise. ANDI seems to be failing though for these, so that should be fixed before it gets merged (just wants a label on these elements):

image


Another thing to note is that the built in add button for these types of filters brings up a kind of odd looking popup, but thats not for this PR IMO. Great work
image

**Comment by rachidatecs** [comment]
> LGTM code wise and functionality wise. ANDI seems to be failing though for these, so that should be fixed before it gets merged (just wants a label on these elements):
> 
> Another thing to note is that the built in add button for these types of filters brings up a kind of odd looking popup, but thats not for this PR IMO. 

1st item is a pre-existing Django issue that we never caught. See it on the Users page. Also on the users page, the date and time inputs are missing labels. I think this should be tackled in a separate ticket seeing as it's a pre-existing issue that affects more than one kind of component. cc @abroddrick and nicely done catching that.

2nd item: Another django built-in functionality. I don't think there's anything especially janky in the popups, so I'd leave well enough alone.

Finally - we're in process of revising this to allow for change, delete and view buttons in addition to add in that 'related widget.' We should have the PR ready for re-review on Monday.

**Review by Katherine-Osos — APPROVED** [review]

**Comment by rachidatecs** [comment]
> diff change/view/delete button

Right now, analysts have view only into DA > Alternative Domains.

We're done making changes.

**Review by zandercymatics — COMMENTED** [review]
There a bug with the "view" button on the multi selects. The other options (delete, edit, etc) open in a new tab, but view opens in the same window context. My guess is that this is because it is missing "&_popup=1". 
image
image

**Pull request merged**
