### PR TITLE
Post-request submission content updates

### PR DESCRIPTION
**Pull request by michelle-rago**
Resolves [770](https://github.com/orgs/cisagov/projects/26/views/38?filterQuery=assignee%3A%22michelle-rago%22#:~:text=Content%3A%20Clarify%20next%20steps%20on%20Confirmation%20page), [778](https://github.com/cisagov/manage.get.gov/issues/778)

Changes
- Aligned post-request submission content re: next steps
- Simplified log in statement on 403 error page
- Tightened up pre-submission modal text

### CODE REVIEW

**Comment by Katherine-Osos** [comment]
@michelle-rago The content looks great! Two notes: 
- During the last round of testing with analysts, Alex walked through the request flow and made a suggestion for this confirmation page. He thought we may want to add a link to the contact form. That being said, there was debate on whether this is when someone would contemplate contacting us. What are your thoughts on this? 
- This page kinda feels like a dead end. What do you think about adding a button to "Return to dashboard" (may want to use different language)? The contextual link to "check the status" leads to the dashboard, too, but that might not be an obvious doorway for leaving the page. Any opinion on this?

**Comment by michelle-rago** [comment]
Resolved https://github.com/cisagov/manage.get.gov/issues/1478

**Comment by gabydisarli** [comment]
@michelle-rago I realized you responded to the comments I made in the google doc but I never replied. Sorry about that!

**Comment by gabydisarli** [comment]
> > @michelle-rago The content looks great! Two notes:
> > 
> > * During the last round of testing with analysts, Alex walked through the request flow and made a suggestion for this confirmation page. He thought we may want to add a link to the contact form. That being said, there was debate on whether this is when someone would contemplate contacting us. What are your thoughts on this?
> > * This page kinda feels like a dead end. What do you think about adding a button to "Return to dashboard" (may want to use different language)? The contextual link to "check the status" leads to the dashboard, too, but that might not be an obvious doorway for leaving the page. Any opinion on this?
> 
> I did add the contact form to the request review page. I think it makes sense to also add it to the confirmation page. I just did that.
> 
> I'm not sure about another link to the dashboard. Users can use the ".gov Registrar" link. And we have the footer links too.

I agree with not adding any button or another link to the dashboard. I think the check your status link works nicely.

**Comment by gabydisarli** [comment]
I'm still feeling like something is missing here:

> We’ll email you if we have questions and when we complete our review. 

It seems like a person from CISA/.gov will email them if they have questions and when they complete their review. Is there a way we can separate these ideas so that it's clear that:

1. a real human will contact them if they have questions and 
2. when the review is completed they'll receive an automated email

?

**Comment by gabydisarli** [comment]
On the character limit bug. When I enter more than the allowed character I do see the counter update. It shows the numbers turning red to indicate how many characters I am over the limit, however, I'm allowed to save and continue without getting an error and am able to proceed. When I return to that page I see the counter has reset to `1000 characters allowed`.

**Comment by michelle-rago** [comment]
> On the character limit bug. When I enter more than the allowed character I do see the counter update. It shows the numbers turning red to indicate how many characters I am over the limit, however, I'm allowed to save and continue without getting an error and am able to proceed. When I return to that page I see the counter has reset to `1000 characters allowed`.
> 
> On the purpose of your domain question, I'm stopped from advancing and see our error message summary and in-line
> 
> screencapture-getgov-ko-app-cloud-gov-register-purpose-2023-12-20-13_54_16

@rachidatecs See @gabydisarli's comment above about the character limit issue.

**Comment by michelle-rago** [comment]
> I'm still feeling like something is missing here:
> 
> > We’ll email you if we have questions and when we complete our review.
> 
> It seems like a person from CISA/.gov will email them if they have questions and when they complete their review. Is there a way we can separate these ideas so that it's clear that:
> 
> 1. a real human will contact them if they have questions and
> 2. when the review is completed they'll receive an automated email
> 
> ?

@gabydisarli I don't think we need to make that distinction. Also, do we know that's what will happen for sure in each case? I think a requestor could go back and forth with an analyst and be informed that a review is complete, or that a domain is approved, before they get an automated email. Can you explain more about what you think would be useful here? Do you think it's important to say that they'll receive an automated email?

**Comment by Katherine-Osos** [comment]
I think we need to decouple the issues with character counter from this ticket so we can get the content changes merged. Also, there's already a ticket for the character counter resetting here: #1480

**Comment by Katherine-Osos** [comment]
@michelle-rago 
1) I still feel like a button would be nice on this page; a clear doorway out. But it sounds like I'm in the minority, so let's leave as is for now!
2) Agree with you that it doesn't seem necessary to distinguish how each email is initiated. 
3) I have some suggestions for rearranging the last paragraph, though. [See the Google Doc](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.1jlao46).

**Review by Katherine-Osos — APPROVED** [review]

**Comment by Katherine-Osos** [comment]
LGTM! (aside from character counter issues)

**Pull request merged**
